apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-project2
  labels:
    app: python-project2
spec:
    replicas: 4
    selector:
      matchLabels:
        app: python-project2
    template:
      metadata:
        labels:
          app: python-project2
      spec:
        containers:
          - name: python-project
            image: tyagianant98/python-project:17
            ports:
              - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: python-project2
  labels:
    apps: python-project2
spec:
  selector:
    app: python-project2
  type: LoadBalancer
  ports:
    - port: 8080
      name: http
      targetPort: 8080

